# Workflow to deploy static content to GitHub Pages 

# name of this workflow 
name: Deploy static content to Pages 

# defines which event to trigger workflow 
on:
  # triggers workflow on push request events for the "main" branch
  push:
    branches: [ "main" ]

  # enables "Run workflow" button on Actions tab to run workflow manually 
  workflow_dispatch:

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment as top-level key
permissions: 
      contents: read 
      pages: write # to deploy to pages 
      id-token: write # to verify the deployment originates from an appropriate source

# workflow contains a single job called "deploy"
jobs:
  deploy: # name of job 
      # defines environment object that the job references 
      environment:
        name: github-pages # environment name 
        url: https://euniceyoh.github.io/ # environment url 
      # type of runner that the job will run on, specifies operating system 
      runs-on: ubuntu-latest 
      # represent a sequence of tasks that will be executed as part of the job
      steps: 
        - name: Checkout # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          uses: actions/checkout@v3
        - name: Setup Pages # enable Pages and extract various metadata about a site
          uses: actions/configure-pages@v3 
        - name: Upload artifact # packaging and uploading artifact that can be deployed to Pages
          uses: actions/upload-pages-artifact@v1
          with: 
            path: '.' # Upload entire repository 
        - name: Deploy to Github Pages # deploy artifacts to github pages 
          uses: actions/deploy-pages@v2 
  

